version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  bootstrap:
    build:
      context: .
      dockerfile: cmd/bootstrap/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: postgres
      DB_HOST: postgres
      DB_PORT: 5432

  api:
    restart: always
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: postgres
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  postgres_data: {}
