/*
Liteflag API

API for managing feature flags.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Flag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Flag{}

// Flag struct for Flag
type Flag struct {
	// Unique identifier for the feature flag
	Key string `json:"key"`
	// Type of the flag value
	Type string `json:"type"`
	// Whether or not the flag is public.
	IsPublic bool `json:"isPublic"`
	Value FlagValue `json:"value"`
}

type _Flag Flag

// NewFlag instantiates a new Flag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFlag(key string, type_ string, isPublic bool, value FlagValue) *Flag {
	this := Flag{}
	this.Key = key
	this.Type = type_
	this.IsPublic = isPublic
	this.Value = value
	return &this
}

// NewFlagWithDefaults instantiates a new Flag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFlagWithDefaults() *Flag {
	this := Flag{}
	return &this
}

// GetKey returns the Key field value
func (o *Flag) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *Flag) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *Flag) SetKey(v string) {
	o.Key = v
}

// GetType returns the Type field value
func (o *Flag) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Flag) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Flag) SetType(v string) {
	o.Type = v
}

// GetIsPublic returns the IsPublic field value
func (o *Flag) GetIsPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
func (o *Flag) GetIsPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *Flag) SetIsPublic(v bool) {
	o.IsPublic = v
}

// GetValue returns the Value field value
func (o *Flag) GetValue() FlagValue {
	if o == nil {
		var ret FlagValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Flag) GetValueOk() (*FlagValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Flag) SetValue(v FlagValue) {
	o.Value = v
}

func (o Flag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Flag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["type"] = o.Type
	toSerialize["isPublic"] = o.IsPublic
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *Flag) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"type",
		"isPublic",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFlag := _Flag{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFlag)

	if err != nil {
		return err
	}

	*o = Flag(varFlag)

	return err
}

type NullableFlag struct {
	value *Flag
	isSet bool
}

func (v NullableFlag) Get() *Flag {
	return v.value
}

func (v *NullableFlag) Set(val *Flag) {
	v.value = val
	v.isSet = true
}

func (v NullableFlag) IsSet() bool {
	return v.isSet
}

func (v *NullableFlag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFlag(val *Flag) *NullableFlag {
	return &NullableFlag{value: val, isSet: true}
}

func (v NullableFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFlag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


