name: test-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: make test

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2  # Adjust the version as needed
        golangci-lint --version

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Build API
      run: make build-api

    - name: Build bootstrap
      run: make build-bootstrap

    - name: Build API image
      run: make docker-build-api

    - name: Build bootstrap image
      run: make docker-build-bootstrap
