name: test-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v ./...

    - name: Docker build API
      run: make docker-build-api

    - name: Docker build bootstrap
      run: make docker-build-bootstrap

